Vagrant.configure("2") do |config|

  config.vm.define "nexus" do |nexus|
    nexus.vm.box = "bento/ubuntu-24.04"
    nexus.vm.hostname = "nexus-server"

    # Give it a static Private IP so the DB can talk to it
    nexus.vm.network "private_network", ip: "192.168.56.66"

    # Allocate RAM and CPU
    nexus.vm.provider "virtualbox" do |vb|
      vb.name = "nexus_Node"
      vb.memory = "4096"
      vb.cpus = 2
    end
  end
end
