Vagrant.configure("2") do |config|
  
  config.vm.define "aws" do |aws|
    aws.vm.box = "bento/ubuntu-24.04"
    aws.vm.hostname = "aws-server"

    # Give it a static Private IP so the DB can talk to it
    aws.vm.network "private_network", ip: "192.168.56.30"

    # Allocate RAM and CPU
    aws.vm.provider "virtualbox" do |vb|
      vb.name = "aws_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
end
