Vagrant.configure("2") do |config|

  # ==========================================
  # VM 1: For Controller Node
  # ==========================================
  config.vm.define "ncblc" do |ncblc|
    ncblc.vm.box = "bento/ubuntu-24.04"
    ncblc.vm.hostname = "ncblc-server"

    # Give it a static Private IP so the DB can talk to it
    ncblc.vm.network "private_network", ip: "192.168.56.20"

    # Allocate RAM and CPU
    ncblc.vm.provider "virtualbox" do |vb|
      vb.name = "ncblc_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # ==========================================
  # VM 2: For Worker Node
  # ==========================================
  config.vm.define "ncblw" do |ncblw|
    ncblw.vm.box = "bento/ubuntu-24.04"
    ncblw.vm.hostname = "ncblw-server"

    # Give it a DIFFERENT static Private IP
    ncblw.vm.network "private_network", ip: "192.168.56.21"

    # Allocate RAM and CPU
    ncblw.vm.provider "virtualbox" do |vb|
      vb.name = "ncblw_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

end  
