Vagrant.configure("2") do |config|

  # ==========================================
  # VM 1: For Controller Node
  # ==========================================
  config.vm.define "ncblc" do |ncblc|
    ncblc.vm.box = "bento/ubuntu-24.04"
    ncblc.vm.hostname = "ncblc-server"

    # Give it a static Private IP so the DB can talk to it
    ncblc.vm.network "private_network", ip: "192.168.56.20"

    # Allocate RAM and CPU
    ncblc.vm.provider "virtualbox" do |vb|
      vb.name = "ncblc_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # ==========================================
  # VM 2: For Worker Node as a web
  # ==========================================
  config.vm.define "ncblw" do |ncblw|
    ncblw.vm.box = "bento/ubuntu-24.04"
    ncblw.vm.hostname = "ncblw-server"

    # Give it a DIFFERENT static Private IP
    ncblw.vm.network "private_network", ip: "192.168.56.21"

    # Allocate RAM and CPU
    ncblw.vm.provider "virtualbox" do |vb|
      vb.name = "ncblw_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # ==========================================
  # VM 3: For Worker Node as a database practice
  # ==========================================
  config.vm.define "ncbld" do |ncbld|
    ncbld.vm.box = "eurolinux-vagrant/centos-stream-9"
    ncbld.vm.hostname = "ncbld-server"

    # Give it a DIFFERENT static Private IP
    ncbld.vm.network "private_network", ip: "192.168.56.22"

    # Allocate RAM and CPU
    ncbld.vm.provider "virtualbox" do |vb|
      vb.name = "ncbld_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end
  
  # ==================================================
  # VM 4: For database of wordpress deploy
  # ==================================================
  config.vm.define "ncbldw" do |ncbldw|
    ncbldw.vm.box = "bento/ubuntu-24.04"
    ncbldw.vm.hostname = "ncbldw-server"

    # Give it a DIFFERENT static Private IP
    ncbldw.vm.network "private_network", ip: "192.168.56.23"

    # Allocate RAM and CPU
    ncbldw.vm.provider "virtualbox" do |vb|
      vb.name = "ncbldw_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end

  # ==================================================
  # VM 5: For wordpress deploy
  # ==================================================
  config.vm.define "ncblwp" do |ncblwp|
    ncblwp.vm.box = "bento/ubuntu-24.04"
    ncblwp.vm.hostname = "ncblwp-server"

    # Give it a DIFFERENT static Private IP
    ncblwp.vm.network "private_network", ip: "192.168.56.24"

    # Allocate RAM and CPU
    ncblwp.vm.provider "virtualbox" do |vb|
      vb.name = "ncblwp_Node"
      vb.memory = "1024"
      vb.cpus = 1
    end
  end


end  
